app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'personal-details', 'as' => 'personal-details.'], function () {
	/**
	 * Add New Personal Detail
	 */
	Route::get('/create', 'PersonalDetailsController@create')
		->name('create');

	Route::post('/create', 'PersonalDetailsController@store')
		->name('store');

	Route::get('/{id}', 'PersonalDetailsController@showDetail')
		->name('view');

	Route::get('/', 'PersonalDetailsController@listAll')
		->name('list');
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PersonalDetailsController.php
<?php

namespace App\Http\Controllers;

use ArrayObject;
use Illuminate\Http\Request;
use App\Http\Requests\StorePersonalDetailsRequest;
use Illuminate\Support\Facades\Response;
use Symfony\Component\Intl\Intl;
use App\Services\PersonalDetailsStorage;
use Pagerfanta\View\TwitterBootstrap3View;

/**
* 
*/
class PersonalDetailsController extends Controller
{

    private function view($view = null, $data = [])
    {
        return view($view, $data, [
            'genders' => \Config::get('constants.personal_details.genders'),
            'contactModes' => \Config::get('constants.personal_details.contact_modes'),
            'countries' => Intl::getRegionBundle()->getCountryNames(\Lang::getLocale())
        ]);
    }
	
    /**
     * Show one detail by id
     *
     * @param  int  $id
     * @param PersonalDetailsStorage $storage
     *
     * @return Response
     */
    public function showDetail(PersonalDetailsStorage $storage, $id)
    {
        return $this->view('personal_details.view', ['personalDetails' => $storage->get($id)]);
    }


    /**
     * Show the paginated list
     *
     * @param Request $request
     *
     * @return Response
     */
    public function listAll(Request $request)
    {
        /** @var \Pagerfanta\Pagerfanta $pagerfanta */
        $pagerfanta = \App::make('PersonalDetails\Pagerfanta');
        $pagerfanta->setCurrentPage($request->get('page', 1));
        $pagerfantaBarView = new TwitterBootstrap3View();
        $pagerfantaBarHtml = $pagerfantaBarView->render($pagerfanta, function($page) {
            return route('personal-details.list', ['page' => $page]);
        });

        return $this->view('personal_details.list', [
            'records' => $pagerfanta->getCurrentPageResults(),
            'pagerfantaBarHtml' => $pagerfantaBarHtml
        ]);
    }


    /**
     * Displays form
     *
     * @return Response
     */
    public function create()
    {
        return $this->view('personal_details.create');
    }

    /**
     * Add New Personal Detail
     *
     * @param StorePersonalDetailsRequest $request
     * @param PersonalDetailsStorage $storage
     *
     * @return Response
     */
    public function store(StorePersonalDetailsRequest $request, PersonalDetailsStorage $storage)
    {
        $personalDetails = new ArrayObject($request->all());
        $storage->store($personalDetails);

        if ($request->wantsJson()) {
            return Response::json($personalDetails);
        }

        return redirect()->route('personal-details.list');
    }
}

resources/views/common/errors.blade.php
@if (count($errors) > 0)
        <!-- Form Error List -->
<div class="alert alert-danger">
    <strong>Whoops! Something went wrong!</strong>

    <br><br>

    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{trans('main.title')}}</title>

    <!-- Fonts -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel='stylesheet' type='text/css'>

    <!-- Styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

    <style>
        body {
            font-family: 'Lato';
        }
        .fa-btn {
            margin-right: 6px;
        }
    </style>

    @yield('head')
</head>
<body id="app-layout">
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{trans('main.menu.home')}}
                </a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {{trans('main.menu.personal_details.title')}}
                            <span class="caret"></span>
                        </a>
                      <ul class="dropdown-menu">                      
                            <li>
                                <a href="{{route('personal-details.list')}}">
                                    {{trans('main.menu.personal_details.records')}}
                                </a>
                            </li>
                            <li>
                                <a href="{{route('personal-details.create')}}">
                                    {{trans('main.menu.personal_details.create')}}
                                </a>
                            </li>
                      </ul>
                    </li>                    
                </ul>
            </div>
        </div>
    </nav>

    <div id="page-wrapper">
        @yield('content')
    </div>

            <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    @yield('scripts')
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
</body>
</html>

resources/views/personal_details/create.blade.php
@extends('layouts.main')

@section('head')
    <link href="/lib/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css" rel="stylesheet" />
@endsection

@section('scripts')
    <script src="/lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <!--script src="https://cdnjs.cloudflare.com/ajax/libs/parsley.js/2.4.3/parsley.min.js"></script-->
    <script src="/js/personal-details/create.js"></script>
@endsection

@section('content')

<div class="container">
    <div class="page-header">
        <h2>{{trans('personal_details.title.create')}}</h2>
    </div>
    <!-- Display Validation Errors -->
    @include('common.errors')

    <form action="{{route('personal-details.create')}}" method="POST" class="form-horizontal" id="personal-details-form">
        {{ csrf_field() }}

        <div class="row form-group">
            <div class="col-md-6">
                <label for="name" class="col-sm-4 control-label">{{trans('personal_details.label.name')}}</label>

                <div class="col-sm-8">
                    <input type="text" name="name" id="name" class="form-control" required>
                </div>
                <br/>
                <ul id="error-name"></ul>
            </div>
            <div class="col-md-6">
                <label for="gender" class="col-sm-4 control-label">{{trans('personal_details.label.gender')}}</label>

                <div class="col-sm-8">
                    <select name="gender" id="gender" class="form-control" required>
                        @foreach($genders as $key => $value)
                            <option value="{{$key}}">{{trans('personal_details.gender.' . $value)}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>

        <div class="row form-group">
            <div class="col-md-6">
                <label for="phone" class="col-sm-4 control-label">{{trans('personal_details.label.phone')}}</label>

                <div class="col-sm-8">
                    <input type="tel" name="phone" id="phone" class="form-control" required>
                </div>
                <br/>
                <ul id="error-phone"></ul>
            </div>
            <div class="col-md-6">
                <label for="email" class="col-sm-4 control-label">{{trans('personal_details.label.email')}}</label>

                <div class="col-sm-8">
                    <input type="email" name="email" id="email" class="form-control" required>
                </div>
                <br/>
                <ul id="error-email"></ul>
            </div>
        </div>

        <div class="row form-group">
            <label for="address" class="col-sm-2 control-label">{{trans('personal_details.label.address')}}</label>

            <div class="col-sm-10">
                <input type="text" name="address" id="address" class="form-control">
            </div>
        </div>

        <div class="row form-group">
            <div class="col-md-6">
                <label for="nationality" class="col-sm-4 control-label">{{trans('personal_details.label.nationality')}}</label>

                <div class="col-sm-8">
                    <select name="nationality" id="nationality" class="form-control" required>
                        @foreach($countries as $countryCode => $country)
                            <option value="{{$countryCode}}">{{$country}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <label for="dob" class="col-sm-4 control-label">{{trans('personal_details.label.dob')}}</label>

                <div class="col-sm-8">
                    <input type="text" name="dob" id="dob" class="form-control" data-provide="datepicker"
                           data-date-format="yyyy-mm-dd" data-date-end-date="0d">
                </div>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-md-6">
                <label for="preferred_contact_mode" class="col-sm-4">{{trans('personal_details.label.preferred_contact_mode')}}</label>
                <div class="col-sm-8">
                    <select name="preferred_contact_mode" id="preferred_contact_mode" class="form-control" required>
                        @foreach($contactModes as $key => $value)
                            <option value="{{$key}}">{{trans('personal_details.contact_modes.' . $value)}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>

        <div class="row form-group">
            <label for="educational_background" class="col-sm-2 control-label">{{trans('personal_details.label.educational_background')}}</label>

            <div class="col-sm-10">
                <textarea name="educational_background" id="educational_background" class="form-control"></textarea>
            </div>
        </div>

        <!-- Add Task Button -->
        <div class="form-group col-md-6">
            <div class="col-sm-offset-4 col-sm-8">
                <button type="submit" class="btn btn-default">
                    <i class="fa fa-plus"></i> {{trans('personal_details.add')}}
                </button>
            </div>
        </div>
    </form>
</div>

@endsection

resources/views/personal_details/list.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <div class="page-header">
            <h2>{{trans('personal_details.title.list')}}</h2>
        </div>

        @if(!count($records))
            <div class="alert alert-info">
                {{trans('personal_details.messages.no_records')}}
            </div>
        @else
            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <th>{{trans('personal_details.SN')}}</th>
                        <th>{{trans('personal_details.label.name')}}</th>
                        <th>{{trans('personal_details.label.gender')}}</th>
                        <th>{{trans('personal_details.label.phone')}}</th>
                        <th>{{trans('personal_details.label.email')}}</th>
                        <th>{{trans('personal_details.label.nationality')}}</th>
                        <th>{{trans('personal_details.label.age')}}</th>
                    </tr>
                    @foreach($records as $i => $record)
                        <tr>
                            <td>{{$i + 1}}</td>
                            <td><a href="{{route('personal-details.view', ['id' => $record['id']])}}">{{$record['name']}}</a></td>
                            <td>{{trans('personal_details.gender.' . $genders[$record['gender']])}}</td>
                            <td>{{$record['phone']}}</td>
                            <td>{{$record['email']}}</td>
                            <td>{{$countries[$record['nationality']]}}</td>
                            <td>
                                @if($record['dob'])
                                    {{\Carbon\Carbon::createFromFormat('Y-m-d', $record['dob'])->age}}
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>

            {!! $pagerfantaBarHtml !!}
        @endif
    </div>
@endsection

resources/views/personal_details/view.blade.php
@extends('layouts.main')

@section('content')
    <div class="container">
        <div class="page-header">
            <h2>{{trans('personal_details.title.view')}}</h2>
        </div>
        <div class="row">
            <div class="col-md-6">
                <ul class="list-group">
                  <li class="list-group-item">
                    <span class="badge">{{$personalDetails['name']}}</span>
                    {{trans('personal_details.label.name')}}
                  </li>
                  <li class="list-group-item">
                    <span class="badge">{{$personalDetails['phone']}}</span>
                    {{trans('personal_details.label.phone')}}
                  </li>
                  <li class="list-group-item">
                    <span class="badge">
                        {{$personalDetails['dob']}}
                    </span>
                    {{trans('personal_details.label.dob')}}
                  </li>
                  <li class="list-group-item">
                    <span class="badge">{{$contactModes[$personalDetails['preferred_contact_mode']]}}</span>
                    {{trans('personal_details.label.preferred_contact_mode')}}
                  </li>                                   
                </ul>                
            </div>
            <div class="col-md-6">
                <ul class="list-group">
                  <li class="list-group-item">
                    <span class="badge">
                        {{trans('personal_details.gender.' . $genders[$personalDetails['gender']])}}
                    </span>
                    {{trans('personal_details.label.gender')}}
                  </li>
                  <li class="list-group-item">
                    <span class="badge">{{$personalDetails['email']}}</span>
                    {{trans('personal_details.label.email')}}
                  </li>
                  <li class="list-group-item">
                    <span class="badge">
                        {{$countries[$personalDetails['nationality']]}}
                    </span>
                    {{trans('personal_details.label.nationality')}}
                  </li>                                    
                </ul>                
            </div>            
        </div>
        <div class="row">
            <ul class="list-group">
                <li class="list-group-item">
                    <span class="badge">{{$personalDetails['address']}}</span>
                    {{trans('personal_details.label.address')}}
                </li>
            </ul>
        </div>
        <div class="row">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">{{trans('personal_details.label.educational_background')}}</h3>
              </div>
              <div class="panel-body">
                {!! nl2br(e($personalDetails['educational_background'])) !!}
              </div>
            </div>            
        </div>
    </div>
@endsection